// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCEKPG0FPWmEUBef2Tambvx4p3ISl_QfM',
    appId: '1:464390208750:web:e6d5aab7209c8f7f6107ff',
    messagingSenderId: '464390208750',
    projectId: 'chat-room-cfe43',
    authDomain: 'chat-room-cfe43.firebaseapp.com',
    storageBucket: 'chat-room-cfe43.appspot.com',
    measurementId: 'G-FEJLRE179T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ZhX-aGD-W2boAAvFtf6Sen5oR6yoY74',
    appId: '1:464390208750:android:a79cec7410deb24f6107ff',
    messagingSenderId: '464390208750',
    projectId: 'chat-room-cfe43',
    storageBucket: 'chat-room-cfe43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc7tM71f3Zxk6jhi1cXjfaTQhhv3otC88',
    appId: '1:464390208750:ios:dce9d341b86b6c556107ff',
    messagingSenderId: '464390208750',
    projectId: 'chat-room-cfe43',
    storageBucket: 'chat-room-cfe43.appspot.com',
    iosBundleId: 'com.jayr.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc7tM71f3Zxk6jhi1cXjfaTQhhv3otC88',
    appId: '1:464390208750:ios:eb3ca2b4248327d36107ff',
    messagingSenderId: '464390208750',
    projectId: 'chat-room-cfe43',
    storageBucket: 'chat-room-cfe43.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
